const INPUT_VALIDATION_LENGTH = {
    FEATURE_REQUEST_TITLE: { MIN: 10, MAX: 140 },
    FEATURE_REQUEST_DESCRIPTION: { MIN: 32, MAX: 380 },
    CLAW_NAME: { MAX: 50 },
    USER_NAME: { MAX: 100 },
    SSH_KEY_NAME: { MAX: 100 },
    SSH_KEY_PUBLIC_KEY: { MAX: 10000 },
    SSH_KEYS_PER_ACCOUNT: { MAX: 50 },
    EMAIL: { MAX: 320 },
    FILE_CONTENT: { MAX: 1024 * 1024 },
    ENV_VAR_KEY: { MAX: 256 },
    ENV_VAR_VALUE: { MAX: 10000 },
    VOLUME_SIZE: { MIN: 10, MAX: 10240 },
    CLAWS_PER_ACCOUNT: { MAX: 50 },
    OPEN_FEATURE_REQUESTS_PER_USER: { MAX: 3 },
    TOTAL_FEATURE_REQUESTS: { MAX: 200 },
    IN_PROGRESS_FEATURE_REQUESTS_PER_USER: { MAX: 3 },
    SSH_OUTPUT: { MAX: 5 * 1024 * 1024 },
    SKILLS_DEFAULT_LIMIT: { DEFAULT: 50 }
} as const

export default INPUT_VALIDATION_LENGTH
